### ISSUE TITLE
关于7615

### ISSUE THREAD

**Issue by trublemaker** [hanwckf/mt7615#1]
兄弟，k2p 用 padavan 7615弄好了吗？
前两天找到你的源码，先感谢
下了后，编译过了
得手工启动wifi，2.4G信号超强，。。。。
但是不稳定，数据量一大就断
主要就是下面两个提示，你碰到过没有？

Nov 17 11:09:34 kernel: [41974.257812] FWCmdTimeout: command (ed), ext_cmd_type (25), seq(3), timeout(3000ms)
Nov 17 11:09:34 kernel: [41974.265625] pAd->Flags  = 0x11202006
Nov 17 11:09:34 kernel: [41974.269531] txq qlen = 0
Nov 17 11:09:34 kernel: [41974.273437] rxq qlen = 0
Nov 17 11:09:34 kernel: [41974.273437] kickq qlen = 0
Nov 17 11:09:34 kernel: [41974.277343] ackq qlen = 1
Nov 17 11:09:34 kernel: [41974.281250] tx_doneq.qlen = 0
Nov 17 11:09:34 kernel: [41974.285156] rx_done qlen = 0
Nov 17 11:09:34 kernel: [41974.289062] AndesSendCmdMsg: msg state = 8
Nov 17 11:09:34 kernel: [41974.292968] msg->retry_times = 0
Nov 17 11:11:22 kernel: [42082.371093] 51a, flush one!
Nov 17 11:11:24 kernel: [42084.609375] 775, flush one!
Nov 17 11:11:35 kernel: [42095.515625] 52a, flush one!
Nov 17 11:11:38 kernel: [42098.074218] 750, flush one!
Nov 17 11:11:38 kernel: [42098.777343] 8de, flush one!
Nov 17 11:13:53 kernel: [42233.496093] 9b1, flush one!
Nov 17 11:14:46 kernel: [42286.187500] fc7, flush one!
Nov 17 11:15:12 kernel: [42312.093750] 55d, flush one!
Nov 17 11:15:14 kernel: [42314.398437] 76f, flush one!
Nov 17 11:18:09 kernel: [42489.996093] 7d9, flush one!
Nov 17 11:18:53 kernel: [42533.996093] c4e, flush one!

**Comment by hanwckf** [comment]
请尝试用我的源码构建K2P_DRV固件然后再测试一下能否复现，我这里2.4/5g均可稳定工作……

**Comment by hanwckf** [comment]
> 兄弟，k2p 用 padavan 7615弄好了吗？
> 前两天找到你的源码，先感谢
> 下了后，编译过了
> 得手工启动wifi，2.4G信号超强，。。。。
> 但是不稳定，数据量一大就断
> 主要就是下面两个提示，你碰到过没有？
> 
> Nov 17 11:09:34 kernel: [41974.257812] FWCmdTimeout: command (ed), ext_cmd_type (25), seq(3), timeout(3000ms)
> Nov 17 11:09:34 kernel: [41974.265625] pAd->Flags = 0x11202006
> Nov 17 11:09:34 kernel: [41974.269531] txq qlen = 0
> Nov 17 11:09:34 kernel: [41974.273437] rxq qlen = 0
> Nov 17 11:09:34 kernel: [41974.273437] kickq qlen = 0
> Nov 17 11:09:34 kernel: [41974.277343] ackq qlen = 1
> Nov 17 11:09:34 kernel: [41974.281250] tx_doneq.qlen = 0
> Nov 17 11:09:34 kernel: [41974.285156] rx_done qlen = 0
> Nov 17 11:09:34 kernel: [41974.289062] AndesSendCmdMsg: msg state = 8
> Nov 17 11:09:34 kernel: [41974.292968] msg->retry_times = 0
> Nov 17 11:11:22 kernel: [42082.371093] 51a, flush one!
> Nov 17 11:11:24 kernel: [42084.609375] 775, flush one!
> Nov 17 11:11:35 kernel: [42095.515625] 52a, flush one!
> Nov 17 11:11:38 kernel: [42098.074218] 750, flush one!
> Nov 17 11:11:38 kernel: [42098.777343] 8de, flush one!
> Nov 17 11:13:53 kernel: [42233.496093] 9b1, flush one!
> Nov 17 11:14:46 kernel: [42286.187500] fc7, flush one!
> Nov 17 11:15:12 kernel: [42312.093750] 55d, flush one!
> Nov 17 11:15:14 kernel: [42314.398437] 76f, flush one!
> Nov 17 11:18:09 kernel: [42489.996093] 7d9, flush one!
> Nov 17 11:18:53 kernel: [42533.996093] c4e, flush one!

https://transfer.sh/wvsuL/K2P_nano_3.4.3.9-099.trx

**Comment by trublemaker** [comment]
thanks a lot!
直接用了你的padavan编译过了，能用了。
