### ISSUE TITLE
恳请修复PSM休眠模式！

### ISSUE THREAD

**Issue by ghost** [hanwckf/mt7615#2]
如下：
MAC                PhyMode  BW MCS SGI LDPC STBC TRate RSSI PSM Connect Time
                          VHT     80M   9 YES  YES   NO  433M  -67  NO 00:22:07
                          VHT     80M   7 YES  YES   NO  650M  -70  NO 00:27:42
                          VHT     80M   5  NO  YES   NO  468M  -82  NO 00:27:29
                          VHT     80M   4 YES  YES   NO  390M  -76  NO 00:25:40

无线设备的PSM工作都是不正常的，影响耗电，谢谢！

**Comment by FancyQian** [comment]
@a541619896 
我也遇到这个问题，请问你现在有什么好的办法解决吗？
